### ISSUE TITLE
Replace `passport-openidconnect` with `openid-client`

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#206]
https://github.com/GluuFederation/gluu-passport/issues/204

**Comment by jgomer2001** [comment]
Hi @kdhttps
I quickly checked some of the commits above, nice work. I ended up with some questions/suggestions:

- Usage of discovery is clearly convenient so that we can make `new issuer.Client(...` , however I think that not all OPs support it, ie. the `/.well-known/openid-configuration` is not necessarily there. In that case, if values for `authorization_endpoint`, `userinfo_endpoint`, etc. are supplied explicitly in the oxtrust form, will it work?
- Since passport-openidconnect was dropped, let's not forget about how the migration (upgrade) of current customer setups with passport-openidconnect will use openid-client now, ie. how to transform their providers' data so that it becomes understandable by openid-client. A harder case is handling custom attribute mapping files. I'd say to simply use the new default mapping (`/opt/gluu/node/passport/server/mappings/openid-client.js`) and wait for tickets ...

**Comment by kdhttps** [comment]
Hi @jgomer2001 mate,

About Point 1: Not sure, I need to do R&D on it. I created separate issue for this https://github.com/GluuFederation/gluu-passport/issues/241

About Point 2: I written small tutorial on migration here https://github.com/GluuFederation/tutorials/wiki/Migration-passport-opeidconnect-to-openid-client. I think it is simple and easy.

**Comment by jgomer2001** [comment]
Thanks. About point 2 can you put it in a more "algorithmic" way so that @mbaser can implement the upgrade routine when the time comes?. Migration has to take place automatically but this doc looks more targeted to a end-user

**Comment by kdhttps** [comment]
Agreed guru @jgomer2001 . I've added one more section for upgrade script here https://github.com/GluuFederation/tutorials/wiki/Migration-passport-opeidconnect-to-openid-client#details-for-gluu-ce-upgrade-script 
Please check  and let me know if anything missing

**Comment by jgomer2001** [comment]
Excellent, ty

**Comment by christian-hawk** [comment]
Hey all
> Usage of discovery is clearly convenient so that we can make new issuer.Client(... , however I think that not all OPs support it, ie. the /.well-known/openid-configuration is not necessarily there. In that case, if values for authorization_endpoint, userinfo_endpoint, etc. are supplied explicitly in the oxtrust form, will it work?

@jgomer2001 @kdhttps the scope of the issue is: **Replace passport-openidconnect with openid-client**

You know way more then in this case, I just want to make sure we are not adding features and/or customizations that we already were not having in `passport-openidconnect`.

Have in mind that this issue is a single replacement, any new features should be added as new enhancement issue.

About upgrade routune, well pointed @jgomer2001 .

Thank you all for the collab in this issue, and please ignore my comment if it makes no sense.

**Comment by kdhttps** [comment]
@christian-hawk right, we will cover this in future as a new feature. New issue created here https://github.com/GluuFederation/gluu-passport/issues/241

**Comment by christian-hawk** [comment]
Linking dependant PRs:
- Oxtrust: https://github.com/GluuFederation/oxTrust/issues/2052
- Docs https://github.com/GluuFederation/docs-gluu-server-prod/pull/61
- Upgrade script https://github.com/GluuFederation/community-edition-package/issues/52

Tutorial: https://github.com/GluuFederation/tutorials/wiki/Migration-passport-opeidconnect-to-openid-client
