### ISSUE TITLE
Controls the number of seconds after which Passport refuses authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-passport#7]
An inbound IDP that sends an identity assertion may have authenticated a user sometime in the past. This information is normally sent as part of the identity assertion, whether that's a SAML assertion, an id_token, or some other proprietary format. 

The length of such a "timeout" should be configurable.  The default timeout should be one hour.

This is similar to issue https://github.com/GluuFederation/gluu-Asimba/issues/44

**Comment by arvindsinghtomar** [comment]
@nynymike passport-saml have attribute `requestIdExpirationPeriodMs` to Define the expiration time when a Request ID generated for a SAML request will not be valid if seen in a SAML response in the InResponseTo field.
So in order to set Time-out we can use `requestIdExpirationPeriodMs` param , use just have to specify `requestIdExpirationPeriodMs` param with other params in passport-saml-config.json.

commit  - af1112e7197e60d74e26adec363024029a1ccfcb
