### ISSUE TITLE
Manipulating metadata url may provoke reading arbitrary xml files in filesystem

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#84]
> The following block of code is vulnerable to a path traversal vulnerability that allows an unauthenticated user to read any .xml file from the container that hosts oxPassport: https://github.com/GluuFederation/docker-oxPassport/blob/4.1/static/routes.js#L53-L67 The ":idp" parameter is the injection target

**Comment by bsamuels453** [comment]
you may want to keep this issue off your public bug tracker since any customer running this software can be exploited right now

**Comment by christian-hawk** [comment]
The issue is not directly related to gluu-passport.

It was detected on a k8 env. using `istio-envoy`.

In December 2019 it was detected the **high-severity** according to **CVE-2019-9901**(https://nvd.nist.gov/vuln/detail/CVE-2019-9901) (8.3 score):

_Envoy 1.9.0 and before does not normalize HTTP URL paths. A remote attacker may craft a relative path, e.g., something/../admin, to bypass access control, e.g., a block on /admin. A backend server could then interpret the non-normalized path and provide an attacker access beyond the scope provided for by the access control policy._

As we have a chance to protect users exposed to `envoy` vulnerabilities, I just raised a PR for this issue.
